name: barebones-local-llm-chat
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.26,<2
  - faiss-cpu
  - libgomp
  - pip
  - pip:
      - gradio>=4,<5
      - fastapi<1
      - starlette<1
      - llama-cpp-python
      - sentence-transformers
      - huggingface-hub<0.24
